<script lang="ts">
    import { isSameMonth, format, isWithinInterval, formatISO} from "date-fns";

    export let day: Date;
    export let month: Date;
    export let clickAndDown: boolean;
    export let startDate : Date; 
    export let endDate : Date; 
    export let selectedDates : Map<string, boolean>;

    const dayFormat: string = "d";

    let selected: boolean = false;

    $: {
    	const dateAsString = formatISO(day);
        if (selectedDates.has(dateAsString)) {
            selected = true;
        }
    }
    
    function toggleSelected() {
        clickAndDown = true;
        selected = !selected;
    }

    function mouseOver() {
        if (clickAndDown) {
            selected = !selected;
        }
    }
</script>

{#if isSameMonth(day, month)}
    {#if isWithinInterval(day, {start: startDate, end:endDate})}
        <td class:selected on:mousedown={toggleSelected} on:mouseover={mouseOver}>
            {format(day, dayFormat)}
        </td>
    {:else} 
        <td class="disabled">
            {format(day, dayFormat)}
        </td>
    {/if}
{:else}
    <td class="hidden"/>
{/if}

<style>
    .selected {
        color: white;
        background-color: green;
        border: 1px solid black;
        -webkit-animation: bounce-in-top 1.1s both;
        animation: bounce-in-top 1.1s both;
    }

    .hidden {
        pointer-events: none;
    }

    .disabled {
        color:gray;
        border: 1px solid gray;

    }

    td:not(.hidden) {
        user-select: none;
        text-align: center;
    }

    td:not(.hidden):not(.disabled) {
        cursor: pointer;
        border: 1px solid black;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2021-3-14 1:55:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */
    @-webkit-keyframes bounce-in-top {
        0% {
            -webkit-transform: translateY(-500px);
            transform: translateY(-500px);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
            opacity: 0;
        }
        38% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
            opacity: 1;
        }
        55% {
            -webkit-transform: translateY(-65px);
            transform: translateY(-65px);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        72% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        81% {
            -webkit-transform: translateY(-28px);
            transform: translateY(-28px);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        90% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        95% {
            -webkit-transform: translateY(-8px);
            transform: translateY(-8px);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        100% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
    }
    @keyframes bounce-in-top {
        0% {
            -webkit-transform: translateY(-500px);
            transform: translateY(-500px);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
            opacity: 0;
        }
        38% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
            opacity: 1;
        }
        55% {
            -webkit-transform: translateY(-65px);
            transform: translateY(-65px);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        72% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        81% {
            -webkit-transform: translateY(-28px);
            transform: translateY(-28px);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        90% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        95% {
            -webkit-transform: translateY(-8px);
            transform: translateY(-8px);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        100% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
    }
</style>
